/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
    "./backend-templates/**/*.ftl",
    "../src/main/resources/templates/**/*.ftl",
  ],
  safelist: [
    "overflow-hidden",
    "rounded-xl",
    "rounded-lg",
    "shadow-sm",
    "border",
    "border-b",
    "grid",
    "grid-cols-1",
    "gap-4",
    "gap-6",
    "flex",
    "items-center",
    "justify-between",
    "justify-center",
    "flex-col",
    "p-2",
    "p-4",
    "p-6",
    "px-3",
    "px-6",
    "py-2",
    "py-4",
    "mt-1",
    "mt-3",
    "h-32",
    "w-32",
    "text-lg",
    "text-sm",
    "text-xs",
    "text-center",
    "font-semibold",
    "font-medium",
    "bg-white",
    "bg-gray-50",
    "bg-indigo-50",
    "bg-slate-700",
    "bg-slate-800",
    "bg-slate-900",
    "border-gray-200",
    "border-indigo-100",
    "border-slate-600",
    "border-slate-700",
    "border-cyan-400/20",
    "text-gray-500",
    "text-gray-700",
    "text-gray-900",
    "text-indigo-800",
    "text-white",
    "text-slate-50",
    "text-slate-300",
    "text-cyan-100",
    "md:grid-cols-2",
    "md:col-span-2",
    "md:grid-cols-[1fr_160px]",
  ],
  theme: {
    extend: {},
  },
  plugins: [],
}
